apiVersion: apps/v1
kind: Deployment
metadata:
  name: frs-deployment
  labels:
    app: frs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frs
  template:
    metadata:
      labels:
        app: frs
    spec:
      containers:
      - name: frs
        image: ccass440/frs-pipeline:latest
        ports:
        - containerPort: 9000