apiVersion: v1
kind: Service
metadata:
  name: frs-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frs
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 33333